services:
  ros:
    image: registry.robotics-lab.ru/ros-demo:v2-vscode
    build: .
    container_name: ros
    ports:
      - 8765:8765      # Foxglove Websocket
      - 8000:8000      # OpenVSCode HTTP
      - 8554:8554      # MediaMTX RTSP
      - 8889:8889      # MediaMTX HTTP
      - 8189:8189/udp  # MediaMTX WebRTC
    volumes: [".:/src"]
